#debug: true
spring:
  datasource:
    url: jdbc:mysql://192.168.135.130:3306/waimai?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Root.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true  # 会展示hibernate创建schema
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true  # 在hibernate创建schema之后在执行data.sql
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # 对于非嵌入式的数据库，我们总是需要加载data.sql或者schema.sql的内容
      data-locations: classpath*:sql/data.sql
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace